### ISSUE TITLE
Using only .dic and .lm

### ISSUE THREAD

**Issue by Zohan** [syl22-00/pocketsphinx.js#104]
Is there a way to use PocketSphinx.js without using words or grammars? 
I read in #27 that you just need to remove all references to addWords and addGrammar. 
I tried this with:
`postRecognizerJob({command: 'initialize', data: []},
function() {
if (recorder) recorder.consumers = [recognizer];
});`
The system loaded but didn't recognize any words.

`postRecognizerJob({command: 'initialize', data: [["-dict","kws.dict"]]},
                            function() {
                                        if (recorder) recorder.consumers = [recognizer];
                                        });`
Also did not recognize any words.
Is there something else I need to do?

**Comment by syl22-00** [comment]
You can surely do that, you should:

* Preload the different files (dictionary and language model, so that they are available when the recognizer initializes)
* Add the two files to the data argument when calling `init` (your example is correct but only has one file).
* Make sure everything is right, by looking at the JavaScript console.
* Not add any grammar, or switch back to the default language model, as explained in the docs.

**Comment by Zohan** [comment]
Yep figured it out, I just had file locations mixed up.
Thank you!
