### ISSUE TITLE
how to use it with http  and  post method to upload the voice

### ISSUE THREAD

**Issue by Messilimeng** [syl22-00/pocketsphinx.js#105]
if i have a mp3 or mar file type，how can i upload the file to your server，can i change the file  to stream then upload ？

**Comment by syl22-00** [comment]
First, the whole point of `pocketsphinx.js` is that there is no server involved, recording and recognition all happen in the browser.

Meanwhile, if you want to get your audio from a (audio or video) file, you can get the audio samples using `createMediaElementSource` instead of `createMediaStreamSource` on the audio context.

Some docs here: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaElementSource

**Comment by Messilimeng** [comment]
@syl22-00  ok thanks

**Comment by Messilimeng** [comment]
pocketsphinx.js	4M
pocketsphinx_zh.js  11M
the two js  file size  is so big  ，is it  right or fast  be load in browser

**Comment by Messilimeng** [comment]
@syl22-00  ok thanks
